import { type Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./src/**/*.tsx"],
  theme: {
    borderRadius: {
      none: "0",
      px: "1px",
      "0.5": "2px",
      1: "4px",
      "1.5": "6px",
      2: "8px",
      "2.5": "10px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      13: "52px",
      14: "56px",
      15: "60px",
      16: "64px",
      full: "9999px",
    },
    fontFamily: {
      sans: ["Inter-Variable", "sans-serif"],
      display: ["InterDisplay", "sans-serif"],
      logo: ["GeneralSans-Variable", "sans-serif"],
      mono: ["var(--font-geist-mono)", "monospace"],
    },
    fontSize: {
      3: ["12px", "20px"],
      3.5: ["14px", "24px"],
      4: ["16px", "28px"],
      4.5: ["18px", "32px"],
      5: ["20px", "32px"],
      6: ["24px", "36px"],
      7: ["28px", "40px"],
      8: ["32px", "44px"],
      9: ["36px", "48px"],
      10: ["40px", "52px"],
      11: "44px",
      12: "48px",
      13: "52px",
      14: "56px",
      15: "60px",
      16: "64px",
    },
    screens: {
      "3xs": "300px",
      "2xs": "360px",
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "840px",
      xl: "1024px",
      "2xl": "1280px",
      "3xl": "1400px",
      "4xl": "1600px",
      "5xl": "1800px",
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        highlight: {
          DEFAULT: "hsl(var(--highlight))",
          foreground: "hsl(var(--highlight-foreground))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "scale-in": "scale-in 0.2s ease",
        "scale-out": "scale-out 0.2s ease",
        "fade-in": "fade-in 200ms ease",
        "fade-out": "fade-out 200ms ease",
      },
      backgroundImage: {
        "gradient-light": "linear-gradient(90deg, #BCF3F3 0%, #798FDE 100%)",
        "gradient-dark": "linear-gradient(90deg, #0D8888 0%, #1D3FB5 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
