export const FILE_SOURCES = {
  accordion: "src/components/ui/Accordion.tsx",
  alertDialog: "src/components/ui/AlertDialog.tsx",
  aspectRatio: "src/components/ui/AspectRatio.tsx",
  avatar: "src/components/ui/Avatar.tsx",
  badge: "src/components/ui/Badge.tsx",
  breadcrumb: "src/components/ui/Breadcrumb.tsx",
  button: "src/components/ui/Button.tsx",
  calendar: "src/components/ui/Calendar.tsx",
  callout: "src/components/ui/Callout.tsx",
  card: "src/components/ui/Card.tsx",
  carousel: "src/components/ui/Carousel.tsx",
  checkbox: "src/components/ui/Checkbox.tsx",
  collapsible: "src/components/ui/Collapsible.tsx",
  command: "src/components/ui/Command.tsx",
  contextMenu: "src/components/ui/ContextMenu.tsx",
  dataTable: "src/components/ui/DataTable.tsx",
  dialog: "src/components/ui/Dialog.tsx",
  drawer: "src/components/ui/Drawer.tsx",
  dropdownMenu: "src/components/ui/DropdownMenu.tsx",
  form: "src/components/ui/Form.tsx",
  hoverCard: "src/components/ui/HoverCard.tsx",
  input: "src/components/ui/Input.tsx",
  inputOTP: "src/components/ui/InputOTP.tsx",
  label: "src/components/ui/Label.tsx",
  menubar: "src/components/ui/Menubar.tsx",
  navigationMenu: "src/components/ui/NavigationMenu.tsx",
  pagination: "src/components/ui/Pagination.tsx",
  popover: "src/components/ui/Popover.tsx",
  progress: "src/components/ui/Progress.tsx",
  radioGroup: "src/components/ui/RadioGroup.tsx",
  resizable: "src/components/ui/Resizable.tsx",
  scrollArea: "src/components/ui/ScrollArea.tsx",
  select: "src/components/ui/Select.tsx",
  separator: "src/components/ui/Separator.tsx",
  sheet: "src/components/ui/Sheet.tsx",
  skeleton: "src/components/ui/Skeleton.tsx",
  slider: "src/components/ui/Slider.tsx",
  switch: "src/components/ui/Switch.tsx",
  table: "src/components/ui/Table.tsx",
  tabs: "src/components/ui/Tabs.tsx",
  textarea: "src/components/ui/Textarea.tsx",
  toaster: "src/components/ui/Toaster.tsx",
  toggle: "src/components/ui/Toggle.tsx",
  toggleGroup: "src/components/ui/ToggleGroup.tsx",
  tooltip: "src/components/ui/Tooltip.tsx",
  comboboxDemo:
    "src/components/docs/demos/primitives/combobox/ComboboxDemo.tsx",
  datePickerDemo:
    "src/components/docs/demos/primitives/date-picker/DatePickerDemo.tsx",
  rechartsChart: "src/components/ui/RechartsChart.tsx",
  tailwind: "src/utils/tailwind.ts",
  themeToggle: "src/components/navigation/ThemeToggle.tsx",
  _dialog: "src/components/ui/_Dialog.tsx",
  _menu: "src/components/ui/_Menu.tsx",
  _link: "src/components/ui/_Link.tsx",
};
