import { Tracker } from "~/components/ui/Tracker";

const DATA = [
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-red-600", tooltip: "Major Outage" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-red-600", tooltip: "Major Outage" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-yellow-600", tooltip: "Partial Outage" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
  { color: "bg-emerald-600", tooltip: "Operational" },
];

export default function TrackerDemo() {
  return <Tracker data={DATA} />;
}
